### ISSUE TITLE
Would be great if we could specify a name when uploading a file

### ISSUE THREAD

**Issue by bjorkman** [panghy/openai-java#5]
Today when uploading a file we cant specify a file name (from OpenAIService):

public File uploadFile(String purpose, String filepath) {
        java.io.File file = new java.io.File(filepath);
        RequestBody purposeBody = RequestBody.create(MultipartBody.FORM, purpose);
        RequestBody fileBody = RequestBody.create(MediaType.parse("text"), file);
        MultipartBody.Part body = Part.createFormData("file", filepath, fileBody);
        return (File)execute(this.api.uploadFile(purposeBody, body));
    }

This results in the uploaded file having the complete absolut path as a file name, in my case:

`/opt/apache-tomcat-9.0.62/temp/shopify_data359445609280250727.txt`

Not a big issue, but it reveals stuff about the server environment, and is just really hard to read. Would be great if we had an overloaded method where we can specify the name.

**Comment by panghy** [comment]
fixed in 0.19.9
